[package]
name = "qq-music-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
awc = "3.1.1"
derive_more = "0.99.17"
serde = { version = "1.0.156", features = ["derive"] }
